export const WSURL = "https://typerush-dqce.onrender.com/"
export const INIT = "init_game"
export const PROGRESS = "progress_game"
export const OTHERPLAYERLEFT= "otherplayerleft"
export const GAMEOVER = "game_over"
