export const WSURL = "ws://localhost:8080"
export const INIT = "init_game"
export const PROGRESS = "progress_game"
export const OTHERPLAYERLEFT= "otherplayerleft"
export const GAMEOVER = "game_over"
